# Generated by Django 4.2.6 on 2024-05-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0002_employee_detail_paid_leave_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_detail',
            name='paid_leave_balance',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='sick_leave_balance',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='unpaid_leave_balance',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hris.employee_detail')),
            ],
        ),
    ]
