# Generated by Django 4.2.6 on 2024-05-06 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0003_alter_employee_detail_paid_leave_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='empId',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
