# Generated by Django 4.2.6 on 2024-06-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0005_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
