from django.urls import path,include
from . import views

urlpatterns = [
    path('attendance/', views.attendance,name='attendance'),
    path('attendance/attendanceForm', views.attendanceForm,name='attendanceForm'),
    path('attendance/delete_attendance/<uuid:pk>', views.delete_attendance,name='delete_attendance'),
    path('',views.home,name='home'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('auto_logout/', views.auto_logout, name='auto_logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('demo/', views.demo,name='demo'),
    path('employees/', views.employees,name='employees'),
    path('employees/record/<str:pk>/', views.employee_record,name='employee_record'),
    path('employees/update/<str:pk>/', views.update_record,name='update_record'),
    path('users/', views.users,name='users'),
    path('departments/', views.departments,name='departments'),
    path('departments/delete_department/<str:pk>/', views.delete_department,name='delete_department'),
    path('departments/update/<str:pk>/', views.update_department,name='update_department'),
    path('departments/department_create', views.department_create,name='department_create'),
    path('leaves/', views.leaves,name='leaves'),
    path('leave_apply/',views.leave_apply,name='leave_apply'),
    path('leaves/leave_approval/<str:pk>/', views.leave_approval,name='leave_approval'),
    path('employees/employee_create/',views.employee_create,name='employee_create'),
    path('employees/employee_delete/<str:pk>/',views.employee_delete,name='employee_delete'),
    path('employees/user_create/',views.user_create,name='user_create'),
    path('profile/',views.profile,name='profile'),
    path('profile/change_profile',views.change_profile,name='change_profile'),
    path('profile/update',views.profile_update,name='profile_update'),
]
